### ISSUE TITLE
1.2.1: sphinx warnings `reference target not found`

### ISSUE THREAD

**Issue by kloczek** [tox-dev/pyproject-api#38]
First of all currently it is not possible to use straight `sphinx-build` command to build documentation out of source tree
<details>

```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v5.3.0

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 350, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/pyproject-api-1.2.1/docs/conf.py", line 5, in <module>
    from pyproject_api import __version__
ModuleNotFoundError: No module named 'pyproject_api'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 202, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 172, in read
    namespace = eval_config_file(filename, tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 363, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 350, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/pyproject-api-1.2.1/docs/conf.py", line 5, in <module>
    from pyproject_api import __version__
ModuleNotFoundError: No module named 'pyproject_api'


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 350, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/pyproject-api-1.2.1/docs/conf.py", line 5, in <module>
    from pyproject_api import __version__
```
</details>

This can be fixed by patch like below:
```patch
--- a/docs/conf.py
+++ b/docs/conf.py
@@ -1,5 +1,9 @@
 from __future__ import annotations

+import sys
+import os
+sys.path.insert(0, os.path.abspath("../src"))
+
 from datetime import datetime

 from pyproject_api import __version__
```

This patch adds what is in sphinx example copy.py https://www.sphinx-doc.org/en/master/usage/configuration.html#example-of-configuration-file

Than .. on building my packages I'm using `sphinx-build` command with `-n` switch which shows warmings about missing references. These are not critical issues.

<details>

```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v5.3.0
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 2 added, 0 changed, 0 removed
reading sources... [100%] index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-pyproject-api.3 { changelog } /home/tkloczko/rpmbuild/BUILD/pyproject-api-1.2.1/src/pyproject_api/_frontend.py:docstring of pyproject_api._frontend.Frontend:1: WARNING: py:class reference target not found: abc.ABC
/home/tkloczko/rpmbuild/BUILD/pyproject-api-1.2.1/src/pyproject_api/_frontend.py:docstring of pyproject_api._frontend.Frontend.get_requires_for_build_sdist:1: WARNING: py:class reference target not found: ConfigSettings
/home/tkloczko/rpmbuild/BUILD/pyproject-api-1.2.1/src/pyproject_api/_frontend.py:docstring of pyproject_api._frontend.Frontend.get_requires_for_build_wheel:1: WARNING: py:class reference target not found: ConfigSettings
/home/tkloczko/rpmbuild/BUILD/pyproject-api-1.2.1/src/pyproject_api/_frontend.py:docstring of pyproject_api._frontend.Frontend.get_requires_for_build_editable:1: WARNING: py:class reference target not found: ConfigSettings
/home/tkloczko/rpmbuild/BUILD/pyproject-api-1.2.1/src/pyproject_api/_frontend.py:docstring of pyproject_api._frontend.Frontend.prepare_metadata_for_build_wheel:1: WARNING: py:class reference target not found: Path
/home/tkloczko/rpmbuild/BUILD/pyproject-api-1.2.1/src/pyproject_api/_frontend.py:docstring of pyproject_api._frontend.Frontend.prepare_metadata_for_build_wheel:1: WARNING: py:class reference target not found: ConfigSettings
/home/tkloczko/rpmbuild/BUILD/pyproject-api-1.2.1/src/pyproject_api/_frontend.py:docstring of pyproject_api._frontend.Frontend.prepare_metadata_for_build_editable:1: WARNING: py:class reference target not found: Path
/home/tkloczko/rpmbuild/BUILD/pyproject-api-1.2.1/src/pyproject_api/_frontend.py:docstring of pyproject_api._frontend.Frontend.prepare_metadata_for_build_editable:1: WARNING: py:class reference target not found: ConfigSettings
/home/tkloczko/rpmbuild/BUILD/pyproject-api-1.2.1/src/pyproject_api/_frontend.py:docstring of pyproject_api._frontend.Frontend.build_sdist:1: WARNING: py:class reference target not found: Path
/home/tkloczko/rpmbuild/BUILD/pyproject-api-1.2.1/src/pyproject_api/_frontend.py:docstring of pyproject_api._frontend.Frontend.build_sdist:1: WARNING: py:class reference target not found: ConfigSettings
/home/tkloczko/rpmbuild/BUILD/pyproject-api-1.2.1/src/pyproject_api/_frontend.py:docstring of pyproject_api._frontend.Frontend.build_wheel:1: WARNING: py:class reference target not found: Path
/home/tkloczko/rpmbuild/BUILD/pyproject-api-1.2.1/src/pyproject_api/_frontend.py:docstring of pyproject_api._frontend.Frontend.build_wheel:1: WARNING: py:class reference target not found: ConfigSettings
/home/tkloczko/rpmbuild/BUILD/pyproject-api-1.2.1/src/pyproject_api/_frontend.py:docstring of pyproject_api._frontend.Frontend.build_wheel:1: WARNING: py:class reference target not found: Path
/home/tkloczko/rpmbuild/BUILD/pyproject-api-1.2.1/src/pyproject_api/_frontend.py:docstring of pyproject_api._frontend.Frontend.build_editable:1: WARNING: py:class reference target not found: Path
/home/tkloczko/rpmbuild/BUILD/pyproject-api-1.2.1/src/pyproject_api/_frontend.py:docstring of pyproject_api._frontend.Frontend.build_editable:1: WARNING: py:class reference target not found: ConfigSettings
/home/tkloczko/rpmbuild/BUILD/pyproject-api-1.2.1/src/pyproject_api/_frontend.py:docstring of pyproject_api._frontend.Frontend.build_editable:1: WARNING: py:class reference target not found: Path
done
build succeeded, 16 warnings.
```
</details>

You can peak on fixes that kind of issues in other projects
https://github.com/latchset/jwcrypto/pull/289
https://github.com/click-contrib/sphinx-click/commit/abc31069
https://github.com/latchset/jwcrypto/pull/289
https://github.com/RDFLib/rdflib-sqlalchemy/issues/95
https://github.com/sissaschool/elementpath/commit/bf869d9e
https://github.com/jaraco/cssutils/issues/21
https://github.com/pywbem/pywbem/pull/2895
https://github.com/sissaschool/xmlschema/commit/42ea98f2
https://github.com/RDFLib/rdflib/pull/2036
https://github.com/frostming/unearth/issues/14
https://github.com/pypa/distlib/commit/98b9b89f

**Comment by gaborbernat** [comment]
You know the drill, make a PR if you make the issue, or don't make the issue.

**Comment by gaborbernat** [comment]
You're expected to install the project, not alter the sys.path, before running sphinx-build.
