### ISSUE TITLE
Tox on Python 3.12 fails to build wheels with "error: invalid command 'bdist_wheel'"

### ISSUE THREAD

**Issue by adamchainz** [tox-dev/pyproject-api#82]
## Issue

I've started testing my packages with Python 3.12, but running tox for my setuptools-based package fails with:

```
.pkg: prepare_metadata_for_build_wheel> python /Users/chainz/.pyenv/versions/3.12.0b2/lib/python3.12/site-packages/pyproject_api/_backend.py True setuptools.build_meta
py312-django42: packaging backend failed (code=error: invalid command 'bdist_wheel'), with SystemExit: error: invalid command 'bdist_wheel'
Traceback (most recent call last):
...
error: invalid command 'bdist_wheel'
```

I can fix this by making `wheel` a build dependency in `pyproject.toml`:

```
@@ -1,8 +1,9 @@
 [build-system]
 build-backend = "setuptools.build_meta"
 requires = [
   "setuptools",
+  "wheel",
 ]
```

...but that doesn't seem right, since it's not required for `pip wheel` to succeed.

Perhaps tox should instead be installing `wheel` into the build environment?

## Environment

Provide at least:

- OS: macOS, Ubuntu
- `pip list` of the host Python where `tox` is installed:

```console
Package         Version
--------------- -------
build           0.10.0
cachetools      5.3.1
chardet         5.1.0
click           8.1.3
colorama        0.4.6
Cython          0.29.35
distlib         0.3.6
filelock        3.12.0
packaging       23.1
pip             23.1.2
pip-tools       6.13.0
platformdirs    3.5.1
pluggy          1.0.0
pyproject_api   1.5.1
pyproject_hooks 1.0.0
setuptools      67.8.0
tox             4.6.0
virtualenv      20.23.0
wheel           0.40.0
```

## Output of running tox

Provide the output of `tox -rvv`:

```console
$ python3.12 -m tox -e py312-django42
.pkg: _optional_hooks> python /Users/chainz/.pyenv/versions/3.12.0b2/lib/python3.12/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: get_requires_for_build_sdist> python /Users/chainz/.pyenv/versions/3.12.0b2/lib/python3.12/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: prepare_metadata_for_build_wheel> python /Users/chainz/.pyenv/versions/3.12.0b2/lib/python3.12/site-packages/pyproject_api/_backend.py True setuptools.build_meta
py312-django42: packaging backend failed (code=error: invalid command 'bdist_wheel'), with SystemExit: error: invalid command 'bdist_wheel'
Traceback (most recent call last):
  File "/Users/chainz/Documents/Projects/django-htmx/.tox/.pkg/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/Users/chainz/Documents/Projects/django-htmx/.tox/.pkg/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/Users/chainz/Documents/Projects/django-htmx/.tox/.pkg/lib/python3.12/site-packages/setuptools/dist.py", line 1244, in run_command
    super().run_command(command)
  File "/Users/chainz/Documents/Projects/django-htmx/.tox/.pkg/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/Users/chainz/Documents/Projects/django-htmx/.tox/.pkg/lib/python3.12/site-packages/setuptools/command/dist_info.py", line 104, in run
    bdist_wheel = self.get_finalized_command('bdist_wheel')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chainz/Documents/Projects/django-htmx/.tox/.pkg/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 304, in get_finalized_command
    cmd_obj = self.distribution.get_command_obj(command, create)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chainz/Documents/Projects/django-htmx/.tox/.pkg/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 860, in get_command_obj
    klass = self.get_command_class(command)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chainz/Documents/Projects/django-htmx/.tox/.pkg/lib/python3.12/site-packages/setuptools/dist.py", line 992, in get_command_class
    return _Distribution.get_command_class(self, command)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chainz/Documents/Projects/django-htmx/.tox/.pkg/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 844, in get_command_class
    raise DistutilsModuleError("invalid command '%s'" % command)
distutils.errors.DistutilsModuleError: invalid command 'bdist_wheel'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chainz/.pyenv/versions/3.12.0b2/lib/python3.12/site-packages/pyproject_api/_backend.py", line 90, in run
    outcome = backend_proxy(parsed_message["cmd"], **parsed_message["kwargs"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chainz/.pyenv/versions/3.12.0b2/lib/python3.12/site-packages/pyproject_api/_backend.py", line 32, in __call__
    return getattr(on_object, name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chainz/Documents/Projects/django-htmx/.tox/.pkg/lib/python3.12/site-packages/setuptools/build_meta.py", line 380, in prepare_metadata_for_build_wheel
    self.run_setup()
  File "/Users/chainz/Documents/Projects/django-htmx/.tox/.pkg/lib/python3.12/site-packages/setuptools/build_meta.py", line 338, in run_setup
    exec(code, locals())
  File "<string>", line 1, in <module>
  File "/Users/chainz/Documents/Projects/django-htmx/.tox/.pkg/lib/python3.12/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chainz/Documents/Projects/django-htmx/.tox/.pkg/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/chainz/Documents/Projects/django-htmx/.tox/.pkg/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 215, in run_commands
    raise SystemExit("error: " + str(msg))
SystemExit: error: invalid command 'bdist_wheel'
Backend: run command prepare_metadata_for_build_wheel with args {'metadata_directory': '/Users/chainz/Documents/Projects/django-htmx/.tox/.pkg/.meta', 'config_settings': {'--build-option': []}}
running dist_info
creating /Users/chainz/Documents/Projects/django-htmx/.tox/.pkg/.meta/django_htmx.egg-info
writing /Users/chainz/Documents/Projects/django-htmx/.tox/.pkg/.meta/django_htmx.egg-info/PKG-INFO
writing dependency_links to /Users/chainz/Documents/Projects/django-htmx/.tox/.pkg/.meta/django_htmx.egg-info/dependency_links.txt
writing requirements to /Users/chainz/Documents/Projects/django-htmx/.tox/.pkg/.meta/django_htmx.egg-info/requires.txt
writing top-level names to /Users/chainz/Documents/Projects/django-htmx/.tox/.pkg/.meta/django_htmx.egg-info/top_level.txt
writing manifest file '/Users/chainz/Documents/Projects/django-htmx/.tox/.pkg/.meta/django_htmx.egg-info/SOURCES.txt'
reading manifest file '/Users/chainz/Documents/Projects/django-htmx/.tox/.pkg/.meta/django_htmx.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file '/Users/chainz/Documents/Projects/django-htmx/.tox/.pkg/.meta/django_htmx.egg-info/SOURCES.txt'
creating '/Users/chainz/Documents/Projects/django-htmx/.tox/.pkg/.meta/django_htmx-1.14.0.dist-info'
Backend: Wrote response {'code': "error: invalid command 'bdist_wheel'", 'exc_type': 'SystemExit', 'exc_msg': "error: invalid command 'bdist_wheel'"} to /var/folders/20/lzgtdyzs7wj5fc_90w1h3bhc0000gn/T/pep517_prepare_metadata_for_build_wheel-gh7c6f91.json
.pkg: _exit> python /Users/chainz/.pyenv/versions/3.12.0b2/lib/python3.12/site-packages/pyproject_api/_backend.py True setuptools.build_meta
  py312-django42: FAIL code error: invalid command 'bdist_wheel' (0.15 seconds)
  evaluation failed :( (0.18 seconds)
error: invalid command 'bdist_wheel'
```

## Minimal example

(not so minimal)

Example project PR: https://github.com/adamchainz/django-htmx/pull/341

And test run: https://github.com/adamchainz/django-htmx/actions/runs/5254202716/jobs/9492520273?pr=341

**Comment by gaborbernat** [comment]
PR fixing this is welcome 👍

**Comment by abravalheri** [comment]
> tox uses https://peps.python.org/pep-0517/ and https://peps.python.org/pep-0660 to communicate with the build backend, so we never call any `python setup.py` commands. If you get an error about `bdist_wheel` that means `setuptools` is delegating the PEP-517/PEP-660 call internally to that call and fails.
> 
> My hunch is that `prepare_metadata_for_build_wheel` requires calling first [get_requires_for_build_wheel](https://peps.python.org/pep-0517/#get-requires-for-build-wheel) which https://github.com/tox-dev/pyproject-api fails to do per logs above. This is a bug in that project.

This seems to be the key, `get_requires_for_build_wheel` should be called before `prepare_metadata_for_build_wheel` as per PEP 517.

**Comment by gaborbernat** [comment]
Seems the issue was in tox so closing here.
